language: cpp
branches:
    # We need to whitelist the branches which we want to have "push" automation.
    # Pull request automation is not constrained to this set of branches.
    only:
        - develop
        - release
        - /travis/
        - hunter

os: osx
osx_image: xcode9
git:
    depth: 2
    submodules: false
cache:
    directories:
        - ~/.ethash
        - ~/.local
        - ~/Library/Caches/Homebrew
        # Cache whole deps dir hoping you will not need to download and
        # build external dependencies next build.
        - $TRAVIS_BUILD_DIR/build/deps
before_install:
    - git submodule update --init --depth 2
install:
    - ./scripts/install_deps.sh
    - homebrew install ninja
before_script:
    - mkdir -p build && cd build
    - cmake .. -G Ninja -DCOVERAGE=ON
    - cmake --build . -- -j8
script:
    - build/test/testeth
after_success:
    - pip install codecov
    - cd build && codecov
after_script:
    # Hunter: upload cache to the cache server.
#    - if [[ "$TRAVIS_EVENT_TYPE" != "pull_request" ]]; then pip install requests && make -C $TRAVIS_BUILD_DIR/build hunter_upload_cache; fi
